apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  - "airflow.k8s.io"
  - "apps"
  - "policy"
  - "app.k8s.io"
  - "rbac.authorization.k8s.io"
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - airflowbases
  - airflowclusters
  - secrets
  - serviceaccounts
  - services
  - statefulsets
  - rolebindings
  - poddisruptionbudgets
  - applications
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
