apiVersion: airflow.k8s.io/v1alpha1
kind: AirflowCluster
metadata:
  name: cl-cluster
spec:
  executor: Local
  scheduler:
    version: "1.10.2"
  ui:
    replicas: 1
    version: "1.10.2"
  airflowbase:
    name: cc-base
