apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
  annotations:
    {{range $k,$v := .Cluster.Spec.Annotations }}
    {{$k}}: {{$v}}
    {{end}}
spec:
  replicas: {{.Cluster.Spec.Flower.Replicas}}
  selector:
    matchLabels:
      {{range $k,$v := .Selector }}
      {{$k}}: {{$v}}
      {{end}}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        {{range $k,$v := .Labels }}
        {{$k}}: {{$v}}
        {{end}}
      annotations:
        {{range $k,$v := .Cluster.Spec.Annotations }}
        {{$k}}: {{$v}}
        {{end}}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        {{range $k,$v := .Cluster.Spec.NodeSelector }}
        {{$k}}: {{$v}}
        {{end}}
      containers:
      - name: flower
        args:
        - flower
        image: {{.Cluster.Spec.Flower.Image}}:{{.Cluster.Spec.Flower.Version}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
          name: flower
        volumeMounts:
        - mountPath: /usr/local/airflow/dags/
          name: dags-data
      volumes:
      - emptyDir: {}
        name: dags-data
