apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
  annotations:
    {{range $k,$v := .Base.Spec.Annotations }}
    {{$k}}: {{$v}}
    {{end}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{range $k,$v := .Selector }}
      {{$k}}: {{$v}}
      {{end}}
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  serviceName: {{.SvcName}}
  template:
    metadata:
      labels:
        {{range $k,$v := .Labels }}
        {{$k}}: {{$v}}
        {{end}}
      annotations:
        {{range $k,$v := .Base.Spec.Annotations }}
        {{$k}}: {{$v}}
        {{end}}
    spec:
      terminationGracePeriodSeconds: 30 ## check this change to 180 ?
      nodeSelector:
        {{range $k,$v := .Base.Spec.NodeSelector }}
        {{$k}}: {{$v}}
        {{end}}
      containers:
      - name: nfs-server
        image: {{.Base.Spec.Storage.Image}}:{{.Base.Spec.Storage.Version}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 111
          name: rpcbind
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /exports
          name: data
      restartPolicy: Always
      {{if .Base.Spec.Storage.Volume}}
      {{else}}
      volumes:
      - emptyDir: {}
        name: data
      {{end}}
