apiVersion: v1
kind: Secret
metadata:
  name: {{.SecretName}}
  namespace: {{.Namespace}}
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
data:
  {{range $k,$v := .Secret }}
  {{$k}}: {{$v}}
  {{end}}
