kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: asia-southeast1-a
