apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
  annotations:
    {{range $k,$v := .Cluster.Spec.Annotations }}
    {{$k}}: {{$v}}
    {{end}}
spec:
  replicas: {{.Cluster.Spec.Worker.Replicas}}
  selector:
    matchLabels:
      {{range $k,$v := .Selector }}
      {{$k}}: {{$v}}
      {{end}}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        {{range $k,$v := .Labels }}
        {{$k}}: {{$v}}
        {{end}}
      annotations:
        {{range $k,$v := .Cluster.Spec.Annotations }}
        {{$k}}: {{$v}}
        {{end}}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        {{range $k,$v := .Cluster.Spec.NodeSelector }}
        {{$k}}: {{$v}}
        {{end}}
      containers:
      - name: worker
        args:
        - worker
        image: {{.Cluster.Spec.Worker.Image}}:{{.Cluster.Spec.Worker.Version}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8793
          name: wlog
        volumeMounts:
        - mountPath: /usr/local/airflow/dags/
          name: dags-data
      volumes:
      - emptyDir: {}
        name: dags-data
